In [46]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

- OneHotEncoder, if categories == 'auto', take everything as columns to be categorized
- if None in values, it will genrate an extra column to denote None

In [52]:
enc = OneHotEncoder(handle_unknown='error', sparse=False, categories='auto')
X = [['Male', 1], ['Female', 2], ['Female', 3], [None, 1]]
enc.fit(X)

OneHotEncoder(sparse=False)

In [53]:
transformed = enc.transform(X)
transformed

array([[0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0., 0.]])

In [54]:
enc.inverse_transform(transformed)

array([['Male', 1],
       ['Female', 2],
       ['Female', 3],
       [None, 1]], dtype=object)

In [55]:
enc.get_feature_names_out(['gender', 'grade'])

array(['gender_Female', 'gender_Male', 'gender_None', 'grade_1',
       'grade_2', 'grade_3'], dtype=object)

- try drop parameter
    -  if_binary: keeps only 1 col for binary categories(None not included)
    -  first: every category drops 1 level column

In [60]:
enc = OneHotEncoder(handle_unknown='error', sparse=False, categories='auto', drop='if_binary')
X = [['Male', 1], ['Female', 2], ['Female', 3], ['Male', 1]]
enc.fit(X)
transformed = enc.transform(X)
print(transformed)
enc.get_feature_names_out(['gender', 'grade'])

[[1. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 1. 0. 0.]]


array(['gender_Male', 'grade_1', 'grade_2', 'grade_3'], dtype=object)

In [61]:
enc = OneHotEncoder(handle_unknown='error', sparse=False, categories='auto', drop='first')
X = [['Male', 1], ['Female', 2], ['Female', 3], ['Male', 1]]
enc.fit(X)
transformed = enc.transform(X)
print(transformed)
enc.get_feature_names_out(['gender', 'grade'])

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


array(['gender_Male', 'grade_2', 'grade_3'], dtype=object)